### ISSUE TITLE
global `modifiedTokens` cause memory leak

### ISSUE THREAD

**Issue by tripodsan** [markedjs/html-differ#156]
the module global

```
const modifiedTokens = {};
```

is updated with:

```
  modifiedTokens[html] = tokens.split(/({{.+?}}(?!})|[{}\(\)\[\]#\*`=:;,.<>"'\/]|\s+)/).filter(i => i);
```

for each diff. after using it about 20k times, my nodejs process goes out of memory.

## suggestion

make them fields of the `HtmlDiffer` class.

**Comment by UziTech** [comment]
I would be happy to accept a PR with your suggestion 😁👍

**Comment by tripodsan** [comment]
> I would be happy to accept a PR with your suggestion 😁👍

ok, I'll look into it over the next days.
