### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by UziTech** [markedjs/html-differ#4]
We should get this on travis-ci

**Comment by joshbruce** [comment]
@UziTech: Done (at least the switch if flipped). Should we do the same with the marked dependencies repo as well?

**Comment by UziTech** [comment]
[markedjs/marked-dependents](https://github.com/markedjs/marked-dependents) doesn't have any tests so it doesn't need to be on travis

**Comment by joshbruce** [comment]
Cool. Just saw the switch and figured I'd ask. Two birds and all that. :)

Closing.
